name: Windows 2019

on:
  pull_request:
    branches: [ main ]

jobs:
  software_cpp:
    name: Software C++
    runs-on: windows-2019
    defaults:
      run:
        shell: bash -l {0} # Source profile for each step
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: choco install gcc-arm-embedded ninja kicad libsndfile
      # libcairo --->
      - run: c:/msys64/usr/bin/bash -lc 'pacman -S mingw-w64-x86_64-gtk3 --noconfirm'
        shell: powershell
      - run: echo "c:/msys64/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH
        shell: powershell
      - run: rm c:/msys64/mingw64/bin/python*
      # <--- libcairo
      - run: pip3 install -r requirements.txt
      - run: cp include/erb/vcvrack/design/d-din/*.otf c:/windows/fonts
      - run: cp include/erb/vcvrack/design/indie-flower/*.ttf c:/windows/fonts
      - run: python build-system/install.py
      #- run: python blocks/test/configure.py
      #- run: python blocks/test/build.py
      - name: test/data
        run: erbb configure; erbb build
        working-directory: test/data
      - name: samples/bypass
        run: erbb configure; erbb build; erbb build hardware; erbb build simulator
        working-directory: samples/bypass
      - name: samples/drop
        run: erbb configure; erbb build; erbb build hardware; erbb build simulator
        working-directory: samples/drop
      - name: samples/reverb
        run: erbb configure; erbb build; erbb build hardware; erbb build simulator
        working-directory: samples/reverb
      - name: samples/kick
        run: erbb configure; erbb build; erbb build hardware; erbb build gerber; erbb build simulator
        working-directory: samples/kick
      - name: erbb init
        run: mkdir init; cd init; erbb init Init; erbb configure; erbb build; erbb build hardware; erbb build simulator
        working-directory: samples

  software_max:
    name: Software Max/MSP/Gen~
    runs-on: windows-2019
    defaults:
      run:
        shell: bash -l {0} # Source profile for each step
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: msys2/setup-msys2@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9' # gyp doesn't support 3.10
          architecture: 'x64'
      - run: choco install gcc-arm-embedded ninja kicad libsndfile
      # libcairo --->
      - run: c:/msys64/usr/bin/bash -lc 'pacman -S mingw-w64-x86_64-gtk3 --noconfirm'
        shell: powershell
      - run: echo "c:/msys64/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH
        shell: powershell
      - run: rm c:/msys64/mingw64/bin/python*
      # <--- libcairo
      - run: pip install -r requirements.txt
      - run: cp include/erb/vcvrack/design/d-din/*.otf c:/windows/fonts
      - run: cp include/erb/vcvrack/design/indie-flower/*.ttf c:/windows/fonts
      - run: python build-system/install.py
      - name: test/max
        run: erbb configure; erbb build simulator; erbb build; erbb build hardware
        working-directory: test/max
      - name: test/max2
        run: erbb configure; erbb build simulator; erbb build; erbb build hardware
        working-directory: test/max2

  hardware:
    name: Hardware
    runs-on: windows-2019
    defaults:
      run:
        shell: bash -l {0} # Source profile for each step
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: choco install kicad
      # libcairo --->
      - run: c:/msys64/usr/bin/bash -lc 'pacman -S mingw-w64-x86_64-gtk3 --noconfirm'
        shell: powershell
      - run: echo "c:/msys64/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH
        shell: powershell
      - run: rm c:/msys64/mingw64/bin/python*
      # <--- libcairo
      - run: ls c:/Program\ Files
      - run: ls -laR c:/Program\ Files/KiCad
      - run: c:/Program\ Files/KiCad/6.0/bin/python.exe blocks/audio-in-daisy/build.py
      - run: c:/Program\ Files/KiCad/6.0/bin/python.exe blocks/audio-out-daisy/build.py
      - run: c:/Program\ Files/KiCad/6.0/bin/python.exe blocks/button/build.py
      - run: c:/Program\ Files/KiCad/6.0/bin/python.exe blocks/cv-in/build.py
      - run: c:/Program\ Files/KiCad/6.0/bin/python.exe blocks/gate-in/build.py
      - run: c:/Program\ Files/KiCad/6.0/bin/python.exe blocks/gate-out/build.py
      - run: c:/Program\ Files/KiCad/6.0/bin/python.exe blocks/led/build.py
      - run: c:/Program\ Files/KiCad/6.0/bin/python.exe blocks/led-bi/build.py
      - run: c:/Program\ Files/KiCad/6.0/bin/python.exe blocks/multiplexer/build.py
      - run: c:/Program\ Files/KiCad/6.0/bin/python.exe blocks/pot/build.py
      - run: c:/Program\ Files/KiCad/6.0/bin/python.exe blocks/power-bus/build.py
      - run: c:/Program\ Files/KiCad/6.0/bin/python.exe blocks/regulator-daisy/build.py
      - run: c:/Program\ Files/KiCad/6.0/bin/python.exe blocks/slider/build.py
      - run: c:/Program\ Files/KiCad/6.0/bin/python.exe blocks/switch/build.py
      - run: c:/Program\ Files/KiCad/6.0/bin/python.exe blocks/trim/build.py
      - run: c:/Program\ Files/KiCad/6.0/bin/python.exe blocks/kits/stats.py
      - run: c:/Program\ Files/KiCad/6.0/bin/python.exe blocks/kits/build.py
      - run: c:/Program\ Files/KiCad/6.0/bin/python.exe boards/kivu12/build.py

  unit_tests:
    name: Unit Tests
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: choco install ninja
      - run: python test/unit/configure.py
      - run: python test/unit/build.py
      - run: python test/unit/run.py

  erbb_tests:
    name: Erbb/Erbui Tests
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: choco install kicad
      # libcairo --->
      - run: c:/msys64/usr/bin/bash -lc 'pacman -S mingw-w64-x86_64-gtk3 --noconfirm'
        shell: powershell
      - run: echo "c:/msys64/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH
        shell: powershell
      - run: rm c:/msys64/mingw64/bin/python*
      # <--- libcairo
      - run: pip3 install -r requirements.txt
      - run: cp include/erb/vcvrack/design/d-din/*.otf c:/windows/fonts
      - run: cp include/erb/vcvrack/design/indie-flower/*.ttf c:/windows/fonts
      - run: python build-system/test.py
      - run: python build-system/cover.py
      - run: python test/vcvrack/configure.py
      - run: python test/vcvrack/build.py
