name: Windows 2019

on:
  pull_request:
    branches: [ main ]

jobs:
  software_cpp:
    name: Software C++
    runs-on: windows-2019
    defaults:
      run:
        shell: bash -l {0} # Source profile for each step
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: choco install gcc-arm-embedded ninja libsndfile
      # libcairo --->
      - run: c:/msys64/usr/bin/bash -lc 'pacman -S mingw-w64-x86_64-cairo --noconfirm'
        shell: powershell
      - run: echo "c:/msys64/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH
        shell: powershell
      - run: rm c:/msys64/mingw64/bin/python*
      # <--- libcairo
      - run: pip3 install -r requirements.txt
      - run: cp include/erb/vcvrack/design/d-din/*.otf c:/windows/fonts
      - run: cp include/erb/vcvrack/design/indie-flower/*.ttf c:/windows/fonts
      - run: python build-system/install.py
      - name: test/data
        run: erbb configure && erbb build
        working-directory: test/data
      - name: samples/bypass
        run: erbb configure && erbb build && erbb build simulator
        working-directory: samples/bypass
      - name: samples/drop
        run: erbb configure && erbb build && erbb build simulator
        working-directory: samples/drop
      - name: samples/reverb
        run: erbb configure && erbb build && erbb build simulator
        working-directory: samples/reverb
      - name: samples/kick
        run: erbb configure && erbb build && erbb build gerber && erbb build simulator
        working-directory: samples/kick
      - name: erbb init
        run: mkdir init && cd init && erbb init Init && erbb configure && erbb build && erbb build simulator
        working-directory: samples

  software_max:
    name: Software Max/MSP/Gen~
    runs-on: windows-2019
    defaults:
      run:
        shell: bash -l {0} # Source profile for each step
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: msys2/setup-msys2@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9' # gyp doesn't support 3.10
          architecture: 'x64'
      - run: choco install gcc-arm-embedded ninja libsndfile
      # libcairo --->
      - run: c:/msys64/usr/bin/bash -lc 'pacman -S mingw-w64-x86_64-cairo --noconfirm'
        shell: powershell
      - run: echo "c:/msys64/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH
        shell: powershell
      - run: rm c:/msys64/mingw64/bin/python*
      # <--- libcairo
      - run: pip install -r requirements.txt
      - run: cp include/erb/vcvrack/design/d-din/*.otf c:/windows/fonts
      - run: cp include/erb/vcvrack/design/indie-flower/*.ttf c:/windows/fonts
      - run: python build-system/install.py
      - name: test/max
        run: erbb configure && erbb build simulator && erbb build
        working-directory: test/max
      - name: test/max2
        run: erbb configure && erbb build simulator && erbb build
        working-directory: test/max2
